---
title: "Contributors"
---

## Contributors

In alphabetic order…

Names...

<hr />

**Name**  
{Title} {Institution}

{Brief Bio}

**Jennifer Abel**  
Research Data Management Librarian, University of Calgary

Jennifer Abel is the Research Data Management Librarian at the University of Calgary, having joined the library in May 2023 from the Research Services Office. Prior to coming back to UCalgary in December 2021, after many years away, she was the Training Coordinator for the Portage Network, an RDM-focused initiative of the Canadian Association of Research Libraries, and for the RDM team in the Digital Research Alliance of Canada. Jennifer is the co-chair of the National Training Expert Group for the Canadian RDM Network of Experts. She holds a PhD in Linguistics and an MLIS from the University of British Columbia, and has taught at UCalgary, UBC and Mount Royal.

**Maria Amoros-Teijeiro**  
Research Assistant, University of Victoria

Maria Amoros-Teijeiro is a PhD candidate in Educational Psychology at the University of Victoria. Originally from the Dominican Republic, she holds a bachelor’s degree in Psychology from INTEC (Dominican Republic) and a master’s in Educational Research from the Universidad de Valladolid (Spain). From 2017 to 2022, she taught research methods at INTEC, coordinated a program aimed at introducing young scholars to educational research, and worked as a researcher at the Dominican Institute of Research, Evaluation and Quality in Education (IDEICE). Passionate about data and research, she moved to Victoria, BC in 2022 to begin her doctoral studies.

**Mathew Vis-Dunbar**  
Data Librarian, University of British Columbia, Okangan

Mathew Vis-Dunbar is the Data Librarian at the University of British Columbia's Okanagan (UBCO) campus. In addition to supporting researcher needs related to data, he works with faculty and students to promote open and transparent research practices.

**Nick Rochlin**  
Data Science Librarian, University of Victoria

Nick Rochlin is the Data Science Librarian at the University of Victoria (UVic).  Prior to joining UVic, he was the Research Data Management (RDM) Specialist with the University of British Columbia’s Advanced Research Computing team, where he provided assistance and instruction to researchers in accessing and using digital research infrastructure, as well as all things RDM.  In his current role, he focuses on supporting researchers in RDM and reproducible research workflows, and bridging the gap between UVic’s Library and Research Computing Services.  He has participated in a number of national roles in Canada’s data ecosystem, and is currently the Co-chair of the Digital Research Alliance of Canada’s RDM National Training Expert Group.

## 2025 Volunteers

We would like to thank the following individuals for volunteering their time and expertise throughout the program:

* {Names...}

