project:
  type: website
  output-dir: docs

website:
  title: "RDM Jumpstart"
  google-analytics: "G-KSGZ4ESKQ3"
  favicon: "images/institutions/alliance_favicon.png"
  page-footer:
    left: |
      Exclusive of images, all content is licensed CC BY-NC 4.0<br/>[Attribution-NonCommercial 4.0 International](https://creativecommons.org/licenses/by-nc/4.0/deed.en)<br/>![](/images/institutions/CC-License.png)
    center: |
      ![](/images/institutions/all_logos.png)
    right: |
      Build with [Quarto](https://quarto.org/) & [RStudio from Posit](https://posit.co/).
    border: true
  navbar:
    logo: "images/institutions/Alliance_logo_Symbol.png"
    logo-alt: "Alliance Logo"
    search: true
    left:
      - href: qmd/extras/index.qmd
        text: Home
      - qmd/extras/codeOfConduct.qmd
      - qmd/extras/contributors.qmd
      - qmd/extras/template.qmd

format:
  html:
    theme:
      light: [flatly, style-sheets/styles.scss]
      dark: [darkly, style-sheets/styles.scss]
    toc: true
      
execute:
  echo: false
  warning: false
  
engine: knitr
