project:
  type: website
  output-dir: docs

website:
  title: "RDM Jumpstart"
  google-analytics: "G-KSGZ4ESKQ3"
  favicon: "images/institutions/alliance_favicon.png"
  page-footer:
    left: |
      Exclusive of images, all content is licensed CC BY-NC 4.0<br/>[Attribution-NonCommercial 4.0 International](https://creativecommons.org/licenses/by-nc/4.0/deed.en)<br/>![](/images/institutions/CC-License.png)
    center: |
      ![](/images/institutions/all_logos.png)
    right: |
      Build with [Quarto](https://quarto.org/) & [RStudio from Posit](https://posit.co/).
    border: true
  navbar:
    logo: "images/institutions/Alliance_logo_Symbol.png"
    logo-alt: "Alliance Logo"
    search: true
    left:
      - text: "Day 1"
        menu:
            - qmd/Day01/Day01_Overview.qmd
            - qmd/Day01/Day01_Lesson1.qmd 
            - qmd/Day01/Day01_Lesson2.qmd
            - qmd/Day01/Day01_Lesson3.qmd
            - qmd/Day01/Day01_Lesson4.qmd
      - text: "Day 2"
        menu:
            - qmd/Day02/Day02_Overview.qmd
            - qmd/Day02/Day02_Lesson1.qmd 
            - qmd/Day02/Day02_Lesson2.qmd
            - qmd/Day02/Day02_Lesson3.qmd
            - qmd/Day02/Day02_Lesson4.qmd
      - text: "Day 3"
        menu:
            - qmd/Day03/Day03_Overview.qmd
            - qmd/Day03/Day03_Lesson1.qmd 
            - qmd/Day03/Day03_Lesson2.qmd
            - qmd/Day03/Day03_Lesson3.qmd
            - qmd/Day03/Day03_Lesson4.qmd
            - qmd/Day03/Day03_Lesson5.qmd
      - text: "Day 4"
        menu:
            - qmd/Day04/Day04_Overview.qmd
            - qmd/Day04/Day04_Lesson1.qmd 
            - qmd/Day04/Day04_Lesson2.qmd
      - text: "Day 5"
        menu:
            - qmd/Day05/Day05_Overview.qmd
            - qmd/Day05/Day05_Lesson1.qmd 
            - qmd/Day05/Day05_Lesson2.qmd
            - qmd/Day05/Day05_Lesson3.qmd
            - qmd/Day05/Day05_Lesson4.qmd
      - text: "The Project"
        href: qmd/Day01/00_TheProject.qmd
      - text: "Resources"
        menu:
            - qmd/extras/codeOfConduct.qmd
            - qmd/extras/setup.qmd
            - qmd/extras/contributors.qmd
            - qmd/extras/template.qmd

format:
  html:
    theme:
      light: [flatly, style-sheets/styles.scss]
      dark: [darkly, style-sheets/styles.scss]
    toc: true
    toc-location: left
    callout-icon: false
      
execute:
  warning: false
  error: false
  
engine: knitr
