project:
  type: website
  output-dir: docs

website:
  title: "RDM Jumpstart"
  google-analytics: "G-KSGZ4ESKQ3"
  favicon: "images/institutions/alliance_favicon.png"
  page-footer:
    left: |
      Copyright Statement
    center: |
      Institutional Logos
    right: |
      Build with Quarto
    border: true
  navbar:
    logo: "images/institutions/Alliance_logo_Symbol.png"
    logo-alt: "Alliance Logo"
    search: true
    left:
      - href: qmd/index.qmd
        text: Home
      - qmd/codeOfConduct.qmd
      - qmd/contributors.qmd
      - qmd/template.qmd

format:
  html:
    theme:
      light: [flatly, style-sheets/styles.scss]
      dark: [darkly, style-sheets/styles.scss]
    toc: true
      
execute:
  echo: false
  warning: false
  
engine: knitr
