---
title: "Lesson 3: Data Management Plans"
---

## Learning Objectives

By the end of this lesson, you will be able to:

 - Identify data management plans (DMPs) as a way to maintain good RDM practices.  
 - Recognize the main questions and considerations of a DMP.  
 - Use the DMP Assistant to start a data management plan.  
 - Fill out the DMP sections on data collection, storage, ethics and legal compliance for the example research project using the DMP Assistant.

## Lecture \- Introduction to Data Management Plans

### Lecture

* [Download the PowerPoint](files/day1-L3_DMPs.pptx)

<embed src="files/day1-L3_DMPs.pdf" type="application/pdf" width="100%" height="600px" />


### Lecture Notes

### Data Management Plans (DMPs)

::: {.callout-tip}
## Questions

* Based on what we’ve addressed so far in the course, what do you think a data management plan is?  
* What kind of information would you put in it?
:::

#### What is a DMP?

**A DMP is a document that outlines how research data will be managed during and after a project’s completion.** It is a living document that you will update throughout your project. Remember, the research data lifecycle is iterative and rarely linear. If plans change, or new information is discovered, the decisions must be documented. 

A DMP is a framework based on the stages of the research data lifecycle. It outlines the decisions that you will need to make about data management through the entirety of a research project. You should begin your DMP prior to beginning your research. 

Every DMP will be unique, but they all serve the same purpose. DMPs can:

* help you identify services, tools, workflows, and practices that are best suited to your work.  
* save you time and headaches by anticipating bottlenecks or issues before they occur.  
* enable the preservation of your research data through purposeful planning.  
* promote the transparency and reproducibility of your research.

#### Why Would You Create a DMP?

**Funder Requirements**  
As mentioned in the [“Introduction to RDM”](Day01_Lesson1.html) lesson, the [Tri-Agency RDM Policy](https://science.gc.ca/site/science/en/interagency-research-funding/policies-and-guidelines/research-data-management/tri-agency-research-data-management-policy) has begun rolling out the DMP requirement for certain grant opportunities ([see here for a full list of Tri-Agency competitions that required DMPs](https://science.gc.ca/site/science/en/interagency-research-funding/policies-and-guidelines/research-data-management/funding-opportunities-requiring-data-management-plans)). Whether you are required to create a DMP or not, developing skills in data management, especially as a graduate student, will benefit your own research and the research of every one you work with.

**Research Group/Lab Requirements**  
Standardized practices and documentation guidelines are essential to a well-run project. Onboarding, or training, should occur when new researchers join a lab or project to ensure consistent practices are followed. It is also just as important to review documentation when a lab member leaves the project, as this ensures that transitions are smooth and no data are lost. It is possible that your research lab or group may already have a data management plan in place. Having a group-wide DMP can help large research groups standardize how data is managed across smaller, but interconnected, research projects. Even if you’re not required to create a DMP, it will benefit your research and the work of the lab.

::: {.callout-tip}
## Question

* Have you ever worked on a project that used a DMP?
:::

### The DMP Assistant

The [DMP Assistant](https://dmp-pgd.ca/) is a browser-based tool that helps you create a DMP using structured questions and guidance. It is used by many institutions in Canada, and there are templates and exemplars available for specific disciplines, funding opportunities, or university-specific requirements.

The DMP template we’ll be using for this course is the Alliance Template, which contains 21 questions across seven topical areas. In the next lesson, we are going to use the DMP Assistant to create DMPs that you’ll be completing throughout this course. For reference, the sections and questions in the DMP Assistant are below:

* Data Collection  
  * What types of data will you collect, create, link to, acquire and/or record?  
  * What file formats will your data be collected in? Will these formats allow for data re-use, sharing and long-term access to the data?  
  * What conventions and procedures will you use to structure, name and version-control your files to help you and others better understand how your data are organized?  
* Documentation and Metadata  
  * What documentation will be needed for the data to be read and interpreted correctly in the future?  
  * How will you make sure that documentation is created or captured consistently throughout your project?  
  * If you are using a metadata standard and/or tools to document and describe your data, please list here.  
* Storage and Backup  
  * What are the anticipated storage requirements for your project, in terms of storage space (in megabytes, gigabytes, terabytes, etc.) and the length of time you will be storing it?  
  * How and where will your data be stored and backed up during your research project?  
  * How will the research team and other collaborators access, modify, and contribute data throughout the project?  
* Preservation  
  * Where will you deposit your data for long-term preservation and access at the end of your research project?  
  * Indicate how you will ensure your data is preservation ready. Consider preservation-friendly file formats, ensuring file integrity, anonymization and de-identification, inclusion of supporting documentation.  
* Sharing and Reuse  
  * What data will you be sharing and in what form? (e.g. raw, processed, analyzed, final).  
  * Have you considered what type of end-user license to include with your data?  
  * What steps will be taken to help the research community know that your data exists?  
* Responsibilities and Resources  
  * Identify who will be responsible for managing this project's data during and after the project and the major data management tasks for which they will be responsible.  
  * How will responsibilities for managing data activities be handled if substantive changes happen in the personnel overseeing the project's data, including a change of Principal Investigator?  
  * What resources will you require to implement your data management plan? What do you estimate the overall cost for data management to be?  
* Ethics and Legal Compliance  
  * If your research project includes sensitive data, how will you ensure that it is securely managed and accessible only to approved members of the project?  
  * If applicable, what strategies will you undertake to address secondary uses of sensitive data?  
  * How will you manage legal, ethical, and intellectual property issues?
  
## Activity \- Filling out a DMP

Now that we have learned about the basic structure and questions included in a DMP, we are going to use the DMP Assistant to create a plan for the example project in this course. We will keep returning to this DMP as the course progresses, so that by the end, you will have created your own DMP exemplar to use as a reference for future projects. 

::: {.callout-note}
## Breakout Room

You will work in breakout rooms to discuss the questions of the DMP, but every student will need to fill out their own DMP. Remember that submitting a complete DMP is one of the requirements to obtain a certificate for this course, so take advantage of this time to complete the suggested questions. 

You will have 40 minutes to complete this activity.
:::

### Familiarize Yourself with the DMP Assistant

Watch this YouTube video to familiarize yourself with the DMP Assistant:

[DMP Assistant Video Tutorial Series: Introduction to DMP Assistant](https://www.youtube.com/watch?v=N_Mzq60D4nc)

### Log in to the DMP Assistant

1\. Navigate to the DMP Assistant: [https://dmp-pgd.ca/](https://dmp-pgd.ca/)   
2\. Log in if you have an account already. If you have not yet signed up for a DMP Assistant account, follow the instructions on the video above.

### Create a DMP

1\. Select create a plan. Under “What research project are you planning”, add a name that best describes the example project for this course. Also remember to select “mock project for testing, practice, or educational purposes”.  
2\. Fill out the name of your institution. Once you enter in an institution name, a list of options will appear with any institution-specific templates at the top. Select the Alliance Template. 

### Fill Out Basic Information About the Project

1\. At the top of the page, you will see tabs with Project Details, Contributors, Plan overview, Write Plan, Research Outputs, Share, and Download. Navigate through these tabs to get a sense of what the RDM Assistant entails.

2\. Fill out as much as you can in the tabs Project Details and Contributors using the [project description](00_TheProject.html). It is okay if some sections are left blank as this is an example project. In real life, you will want to fill out all the information.

### Start Writing the DMP

1\. Navigate to the tab “Write Plan”. This is where you write the bulk of your data management plant. You will see that this opens a page with seven collapsible sections, each with 2-3 questions that you should answer to finish your data management plan.

2\. Today, we are going to fill out the questions below. To fill out each question, feel free to read through the [project description](00_TheProject.html) again, and discuss with your colleagues what you think should go in each section. You can type in your ideas in bullet-point format if you prefer.

    - Section 1: Data Collection  
        - What types of data will you collect, create, link to, acquire and/or record?  
        - What file formats will your data be collected in? Will these formats allow for data re-use, sharing and long-term access to the data?

    - Section 3: Storage and Back-up  
        - What are the anticipated storage requirements for your project, in terms of storage space (in megabytes, gigabytes, terabytes, etc.) and the length of time you will be storing it?  
        - How and where will your data be stored and backed up during your research project?  
        - How will the research team and other collaborators access, modify, and contribute data throughout the project?

    - Section 7: Ethics and Legal Compliance  
        - If your research project includes sensitive data, how will you ensure that it is securely managed and accessible only to approved members of the project?  
        - If applicable, what strategies will you undertake to address secondary uses of sensitive data?  
        - How will you manage legal, ethical, and intellectual property issues?



