---
title: "Overview"
---

## Overview

Now that you are familiar with the basics of R, we’re going to learn how to clean our data so that we can begin to explore and analyze it. We will start with a discussion about data cleaning best practices, and then we will use functions from the `tidyverse` to clean up our example dataset. We will end the day by updating our project documentation to reflect the changes we’ve made to the data.


## Learning Objectives: 

By the end of today, you will be able to: 

 - Describe the importance of data cleaning for the research data lifecycle.  
 - Identify data cleaning needs for an example dataset.  
 - Use the syntax from the `tidyverse` to clean data of an example dataset.  
 - Write reproducible code by applying concepts of literate programming.  
 - Keep DMP and project documentation updated with new information.
 
## Lessons

This day has two lessons:

 - Lesson 1 \- [Data cleaning](Day04_Lesson1.html)  
 - Lesson 2 \- [Documentation update](Day04_Lesson2.html)

You can click on the links above to go to each lesson page. There, you will find the learning objectives for the lesson, as well as all the material you will need to follow along with the course.
